### ISSUE TITLE
Please upgrade to  nRF5 SDK v15.0.0

### ISSUE THREAD

**Issue by IvanFarkas** [mafaneh/ble-ebook-project#2]
Good job with the videos and the eBook.

Could you please upgrade to **[nRF5 SDK v15.0.0](http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk/keydef/PLUGINS_ROOT/com.nordic.infocenter.sdk5.v15.0.0/index.html)**. It was released on **[03/23/2018](https://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/)**

**Comment by mafaneh** [comment]
Thanks, @IvanFarkas!

Yes, I am in the process of doing so. I will be adding it on a separate branch first, and then merge it in once I'm done with migrating the code to use the new SDK APIs.

**Comment by IvanFarkas** [comment]
Awesome. I am dining the upgrade myself as well. It's a nightmare with the includes. Thx.

**Comment by hannthirv** [comment]
Hello,

@mafaneh Do you have some schedule when you start upgrade process ? :)

**Comment by mafaneh** [comment]
@hannthirv I have started the process but had to switch to working on other things. They've made so many changes that break all projects and their compilation!

The plan is to have the code updated and working with the latest SDK by the first week of June (optimistically before the end of May).

**Comment by IvanFarkas** [comment]
Is the **nRF5 SDK v15.0.0** branch complete, please?
When can we get an updated **eBook** and **video**, please?

**Comment by mafaneh** [comment]
@IvanFarkas Unfortunately, I am **still** going through the (painful) process of migrating to SDK 15.0.0. Do you have any specific sections of the code you're interested in running with SDK 15.0.0? Any special video requests?

**Comment by IvanFarkas** [comment]
@mafaneh We all appreciate your effort, Mohammad.
I do not have an urgent need, yet.
Can you provide an **SDK 15** update **ETA**, please?

**Comment by mafaneh** [comment]
Thanks, @IvanFarkas. Expect an update to support SDK 15.0.0. by Sep 15th. I'll be pushing some changes soon to the dev branch, and I'll also make sure I push new changes regularly so everyone can keep up with the progress.

**Comment by IvanFarkas** [comment]
Thanks, @mafaneh. That's great news.

**Comment by mafaneh** [comment]
@IvanFarkas Unfortunately, this update process is a pain, especially the many API changes! I apologize, but it seems it will take longer than I had anticipated. I am working hard on it, and I will push the changes as I complete them for each of the examples, starting with the Hello World examples.

**Comment by IvanFarkas** [comment]
@mafaneh Appreciate the feedback. Please take as much time as needed to do a great job. Thx.

**Comment by IvanFarkas** [comment]
@mafaneh Timing is perfect to make it working with the latest nRF5 SDK v15.2.0 :-)

**Comment by mafaneh** [comment]
Work is being done on the branch migrate-sdk-v15. You can keep up with the changes and follow it here: [https://github.com/mafaneh/ble-ebook-project/tree/migrate-sdk-v15](https://github.com/mafaneh/ble-ebook-project/tree/migrate-sdk-v15)
I started this before 15.2.0, but it's probably a straight-forward upgrade from 15.0.0 to 15.2.0, so I may end up doing that as well.

**Comment by IvanFarkas** [comment]
Thx. Ivan

Ivan Farkas, CEO
TeleCuris, LLC
TeleCuris.com<http://TeleCuris.com>
info@TeleCuris.com

On Dec 12, 2018, at 9:33 AM, Mohammad Afaneh <notifications@github.com<mailto:notifications@github.com>> wrote:


Work is being done on the branch migrate-sdk-v15. You can keep up with the changes and follow it here: https://github.com/mafaneh/ble-ebook-project/tree/migrate-sdk-v15
I started this before 15.2.0, but it's probably a straight-forward upgrade from 15.0.0 to 15.2.0, so I may end up doing that as well.

**Comment by mafaneh** [comment]
The source code is now updated to use SDK v 15.2.0 (on master branch).
