### ISSUE TITLE
Broken link on pdf 4 - Using Bluetooth Developer Studio

### ISSUE THREAD

**Issue by IvanFarkas** [mafaneh/ble-ebook-project#3]
Broken link on pdf 4 - Using Bluetooth Developer Studio

Download BDS plugins (from different vendors – including Nordic Semi):
Broken link. Please update link 

**from**
https://www.bluetooth.com/develop-with-bluetooth/developer-resourcestools/developer-kits/bluetooth-developer-plugins

**to**
https://www.bluetooth.com/develop-with-bluetooth/build/developer-kits/bluetooth-developer-plugins

**Comment by mafaneh** [comment]
Fixed with commit 60f137df668713ec2641dcd2ae5f558b009a586c on master branch
